language: python
python:
    - 3.7
    - 3.8

# command to install dependencies
install:
    - pip3 install --upgrade six
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt
    - pip3 check

# command to run tests
script:
    - make test

notifications:
  email:
    on_success: change
    on_failure: change
