site_name: python-wechaty
repo_url: http://github.com/wechaty/python-wechaty
repo_name: GitHub
site_description: 'python-wechaty AI Chatbot'
copyright: '@wechaty community'
nav:
    - 首页: 'index.md'
    - 介绍:
      - '使用免费Web协议': 'introduction/use-web-protocol.md'
      - '使用Padlocal协议': 'introduction/use-padlocal-protocol.md'
      - '开始上手': 'introduction/getting-started.md'
      - '相关视频': 'introduction/videos.md'
    - 教程: tutorials.md
    - 开箱即用:
      - '如何使用免费Web协议': 'how-to/use-web-protocol.md'
      - '如何使用Padlocal协议': 'how-to/use-padlocal-protocol.md'
      - '如何添加好友': 'how-to/add-friendship.md'
      - '关键字入群': 'how-to/create-room-inviter.md'
      
    # - References: reference
theme:
  name: material
  logo: img/wechaty-icon-white.svg
  favicon: img/favicon.ico

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - toc:
        baselevel: 2

plugins:
    - search